# Generated by Django 5.2.6 on 2025-09-07 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0002_rename_created_at_coach_date_creation_and_more'),
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='equipement',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='coachs.coach'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Musculation guidée', 'Musculation guidée'), ('Poids libres', 'Poids libres'), ('Accessoires', 'Accessoires')], default='Cardio', max_length=50),
        ),
    ]
