# Generated by Django 5.2.6 on 2025-10-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
