# Generated by Django 5.2.6 on 2025-10-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_coach_user_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialite',
        ),
    ]
