# Generated by Django 5.2.6 on 2025-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='coach',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='specialite',
            field=models.CharField(choices=[('Musculation et Force', 'Musculation et Force'), ('Cardio et Endurance', 'Cardio et Endurance'), ('Yoga et Pilates', 'Yoga et Pilates'), ('CrossFit et HIIT', 'CrossFit et HIIT'), ('Préparation physique', 'Préparation physique'), ('Nutrition et Bien-être', 'Nutrition et Bien-être'), ('Rééducation', 'Rééducation'), ('Sports spécifiques', 'Sports spécifiques')], default='Musculation et Force', max_length=50),
        ),
    ]
