# Generated by Django 5.2.6 on 2025-10-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0002_rename_created_at_coach_date_creation_and_more'),
        ('users', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_coaches', to='users.user')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_clients', to='coachs.coach')),
            ],
            options={
                'verbose_name': 'Assignation Coach-Client',
                'verbose_name_plural': 'Assignations Coach-Client',
                'ordering': ['-date_assignation'],
                'unique_together': {('coach', 'client')},
            },
        ),
    ]
