# Generated by Django 5.2.6 on 2025-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0003_coachclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachclient',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], default='PENDING', help_text="Statut de la demande d'assignation", max_length=20),
        ),
    ]
