# Generated by Django 5.2.6 on 2025-09-07 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
        ('users', '0003_rename_created_at_user_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Abonnement', 'verbose_name_plural': 'Abonnements'},
        ),
        migrations.RenameField(
            model_name='abonnement',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='users.user'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='type',
            field=models.CharField(choices=[('Mensuel Standard', 'Mensuel Standard'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Hebdomadaire', 'Hebdomadaire'), ('Annuel Premium', 'Annuel Premium'), ('Pass journée', 'Pass journée'), ('Pass 10 séances', 'Pass 10 séances'), ('VIP', 'VIP')], default='Mensuel Standard', max_length=50),
        ),
    ]
