# Generated by Django 5.2.6 on 2025-09-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coachs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mesures', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='progres', to='users.user')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres_suivis', to='coachs.coach')),
            ],
            options={
                'verbose_name': 'Progrès',
                'verbose_name_plural': 'Progrès',
                'ordering': ['-date'],
            },
        ),
    ]
