# Generated by Django 5.2.6 on 2025-10-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progres', '0001_initial'),
        ('users', '0005_user_coach_user_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progres',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, related_name='progres_suivis', to='users.user'),
        ),
    ]
