# Generated by Django 5.2.6 on 2025-10-03 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachs', '0003_coachclient'),
        ('progres', '0002_alter_progres_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progres',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres_suivis', to='coachs.coach'),
        ),
    ]
